### ISSUE TITLE
A web-compiled version?

### ISSUE THREAD

**Issue by dumblob** [liujiacode/DigitalPalette#3]
This is such a handy tool, that I'd like to use it everywhere I currently am. Could this be compiled to pure javascript client-side application, so that it could be served e.g. by GitHub pages to make it availablle everywhere to everyone 24/7?

**Comment by liujiacode** [comment]
I'm sorry for that, but DigitalPalette is a desktop software, instead of a web application. I'm not sure if it's possible to transform Python into pure Javascript code.

**Comment by dumblob** [comment]
Understood. It was just a question because it's a really useful software. Closing for the lack of actionable items.
